In [2]:
df = pd.read_csv("customer_churn.csv", usecols=['tenure', 'PhoneService', 'InternetService',
                                                                     'Contract','PaymentMethod','MonthlyCharges', 'Churn' ])

In [1]:
import pandas as pd

In [3]:
df.head()

tenure PhoneService InternetService        Contract  \
0       1           No             DSL  Month-to-month   
1      34          Yes             DSL        One year   
2       2          Yes             DSL  Month-to-month   
3      45           No             DSL        One year   
4       2          Yes     Fiber optic  Month-to-month   

               PaymentMethod  MonthlyCharges Churn  
0           Electronic check           29.85    No  
1               Mailed check           56.95    No  
2               Mailed check           53.85   Yes  
3  Bank transfer (automatic)           42.30    No  
4           Electronic check           70.70   Yes

In [4]:
dummy_InternetService = pd.get_dummies(df['InternetService'], prefix='InternetService')
dummy_InternetService

InternetService_DSL  InternetService_Fiber optic  InternetService_No
0                       1                            0                   0
1                       1                            0                   0
2                       1                            0                   0
3                       1                            0                   0
4                       0                            1                   0
...                   ...                          ...                 ...
7038                    1                            0                   0
7039                    0                            1                   0
7040                    1                            0                   0
7041                    0                            1                   0
7042                    0                            1                   0

[7043 rows x 3 columns]

In [5]:
dummy_Contract = pd.get_dummies(df['PaymentMethod'])
dummy_Contract

Bank transfer (automatic)  Credit card (automatic)  Electronic check  \
0                             0                        0                 1   
1                             0                        0                 0   
2                             0                        0                 0   
3                             1                        0                 0   
4                             0                        0                 1   
...                         ...                      ...               ...   
7038                          0                        0                 0   
7039                          0                        1                 0   
7040                          0                        0                 1   
7041                          0                        0                 0   
7042                          1                        0                 0   

      Mailed check  
0                0  
1                1  
2                1  
3                0  
4                0  
...            ...  
7038             1  
7039             0  
7040             0  
7041             1  
7042             0  

[7043 rows x 4 columns]

In [6]:
dummy_PhoneService = pd.get_dummies(df['PhoneService'], drop_first=True, prefix='PhoneService')
dummy_PhoneService

PhoneService_Yes
0                    0
1                    1
2                    1
3                    0
4                    1
...                ...
7038                 1
7039                 1
7040                 0
7041                 1
7042                 1

[7043 rows x 1 columns]

In [8]:
dummy_Churn = pd.get_dummies(df['Churn'], drop_first=True, prefix='Churn')
dummy_Churn

Churn_Yes
0             0
1             0
2             1
3             0
4             1
...         ...
7038          0
7039          0
7040          0
7041          1
7042          0

[7043 rows x 1 columns]

In [9]:
df1 = pd.concat([df, dummy_Churn, dummy_InternetService,dummy_Contract, dummy_PhoneService ], axis=1)

In [10]:
df1.head()

tenure PhoneService InternetService        Contract  \
0       1           No             DSL  Month-to-month   
1      34          Yes             DSL        One year   
2       2          Yes             DSL  Month-to-month   
3      45           No             DSL        One year   
4       2          Yes     Fiber optic  Month-to-month   

               PaymentMethod  MonthlyCharges Churn  Churn_Yes  \
0           Electronic check           29.85    No          0   
1               Mailed check           56.95    No          0   
2               Mailed check           53.85   Yes          1   
3  Bank transfer (automatic)           42.30    No          0   
4           Electronic check           70.70   Yes          1   

   InternetService_DSL  InternetService_Fiber optic  InternetService_No  \
0                    1                            0                   0   
1                    1                            0                   0   
2                    1                            0                   0   
3                    1                            0                   0   
4                    0                            1                   0   

   Bank transfer (automatic)  Credit card (automatic)  Electronic check  \
0                          0                        0                 1   
1                          0                        0                 0   
2                          0                        0                 0   
3                          1                        0                 0   
4                          0                        0                 1   

   Mailed check  PhoneService_Yes  
0             0                 0  
1             1                 1  
2             1                 1  
3             0                 0  
4             0                 1

In [13]:
df1 = df1[['tenure', 'MonthlyCharges', 'InternetService_DSL', 'InternetService_Fiber optic',
           'Bank transfer (automatic)', 'Credit card (automatic)', 'Electronic check', 
           'Mailed check','PhoneService_Yes', 'Churn_Yes']]

In [14]:
df1.head()

tenure  MonthlyCharges  InternetService_DSL  InternetService_Fiber optic  \
0       1           29.85                    1                            0   
1      34           56.95                    1                            0   
2       2           53.85                    1                            0   
3      45           42.30                    1                            0   
4       2           70.70                    0                            1   

   Bank transfer (automatic)  Credit card (automatic)  Electronic check  \
0                          0                        0                 1   
1                          0                        0                 0   
2                          0                        0                 0   
3                          1                        0                 0   
4                          0                        0                 1   

   Mailed check  PhoneService_Yes  Churn_Yes  
0             0                 0          0  
1             1                 1          0  
2             1                 1          1  
3             0                 0          0  
4             0                 1          1

In [15]:
df1.columns

Index(['tenure', 'MonthlyCharges', 'InternetService_DSL',
       'InternetService_Fiber optic', 'Bank transfer (automatic)',
       'Credit card (automatic)', 'Electronic check', 'Mailed check',
       'PhoneService_Yes', 'Churn_Yes'],
      dtype='object')

In [24]:
x = df1.iloc[:,0:9].values
#x.reshape(-1,1)

In [32]:
x

array([[  1.  ,  29.85,   1.  , ...,   1.  ,   0.  ,   0.  ],
       [ 34.  ,  56.95,   1.  , ...,   0.  ,   1.  ,   1.  ],
       [  2.  ,  53.85,   1.  , ...,   0.  ,   1.  ,   1.  ],
       ...,
       [ 11.  ,  29.6 ,   1.  , ...,   1.  ,   0.  ,   0.  ],
       [  4.  ,  74.4 ,   0.  , ...,   0.  ,   1.  ,   1.  ],
       [ 66.  , 105.65,   0.  , ...,   0.  ,   0.  ,   1.  ]])

In [34]:
y = df1.iloc[:,9].values
y.reshape(-1,1)

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]], dtype=uint8)

In [33]:
y

array([0, 0, 1, ..., 0, 1, 0], dtype=uint8)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=50)

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
regressor = LogisticRegression()

In [39]:
regressor.fit(x_train, y_train)

C:\Users\ADMIN\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [41]:
regressor.predict(x_test)

array([0, 0, 0, ..., 0, 0, 1], dtype=uint8)

In [173]:
df.columns

Index(['tenure', 'PhoneService', 'InternetService', 'Contract',
       'PaymentMethod', 'MonthlyCharges', 'Churn'],
      dtype='object')